CREATE TABLE IF NOT EXISTS PROJECT (
	project_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	project_name VARCHAR (255) not null,
	description VARCHAR (255) not null
);

CREATE TABLE IF NOT EXISTS STUFF (
  stuff_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR (255) not null,
  description VARCHAR not null,
  project_id BIGINT not null,
  FOREIGN KEY (project_id)
  REFERENCES PROJECT(project_id)
);

insert into PROJECT (project_name, description) values ('Project X', 'The most secret project in the universe');

insert into STUFF (title, description, project_id) values('A light sabre', 'very very dangerous, but handy', 1);
